help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	rm -rf tmp dist .cache docs site .github/reports .pytest_cache .coverage .github/coverage_html_report
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	git fetch --prune
	git gc --prune=now --aggressive

uv-install:  ## Install uv on your system
	curl -LsSf https://astral.sh/uv/install.sh | sh
	@echo 'export PATH="$$HOME/.local/bin:$$PATH"' >> ~/.bashrc
	@echo 'Installed uv, please re-open your bash terminal or zsh terminal.'

fmt: ## Run pre-commit hooks
	uv run pre-commit run -a

test: ## Run all tests
	uv run pytest

submodule-init: ## Install and update all submodules
	git submodule update --recursive --init

submodule-update:  # Update all submodules
	git submodule update --recursive --remote

gen-docs:  ## Generate documentation
	rm -rf docs
	mkdir -p docs/zh-CN docs/zh-TW
	cp ./README.md ./docs/index.md
	cp ./README.zh-CN.md ./docs/zh-CN/index.md
	cp ./README.zh-TW.md ./docs/zh-TW/index.md
	sed -i \
		-e 's|](README\.md)|](index.md)|g' \
		-e 's|](README\.zh-TW\.md)|](zh-TW/index.md)|g' \
		-e 's|](README\.zh-CN\.md)|](zh-CN/index.md)|g' \
		./docs/index.md
	sed -i \
		-e 's|](README\.md)|](../index.md)|g' \
		-e 's|](README\.zh-TW\.md)|](index.md)|g' \
		-e 's|](README\.zh-CN\.md)|](../zh-CN/index.md)|g' \
		./docs/zh-TW/index.md
	sed -i \
		-e 's|](README\.md)|](../index.md)|g' \
		-e 's|](README\.zh-TW\.md)|](../zh-TW/index.md)|g' \
		-e 's|](README\.zh-CN\.md)|](index.md)|g' \
		./docs/zh-CN/index.md
	uv run ./scripts/gen_docs.py --source ./src --output ./docs/Reference gen_docs
	uv run ./scripts/gen_docs.py --source ./scripts --output ./docs/Scripts gen_docs
	uv run ./scripts/gen_docs.py build_nav
