# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "anyio",
#     "fire",
#     "notebook",
#     "pydantic",
#     "rich",
# ]
# ///
"""Generate and execute Markdown documentation from source files."""

import ast
import shutil
from typing import Literal
import asyncio
from pathlib import Path
from functools import cached_property

import anyio
import nbformat
from pydantic import Field, BaseModel, ConfigDict, computed_field
from nbconvert import MarkdownExporter
from rich.console import Console
from rich.progress import TaskID, Progress
from nbconvert.preprocessors import ExecutePreprocessor

console = Console()


_NAV_START = "  # >>> auto-generated nav (regenerated by `make gen-docs`)"
_NAV_END = "  # <<< auto-generated nav end"


def _nav_indent(level: int) -> str:
    """Indent prefix for a nav item at the given nesting level (top-level = 0)."""
    return "  " + "    " * level


def _build_nav_section(title: str, dir_path: Path, level: int, docs_root: Path) -> list[str]:
    """Render YAML lines for a nav section rooted at `dir_path`.

    Subdirectories are emitted before sibling markdown files so packages
    appear above leaf modules. Returns an empty list if the directory has
    no renderable children.

    Args:
        title (str): Nav label for this directory.
        dir_path (Path): Directory to scan.
        level (int): Zero-based nav nesting depth.
        docs_root (Path): Root used to compute Markdown paths.

    Returns:
        list[str]: YAML lines for this section.
    """
    if not dir_path.is_dir():
        return []

    subdirs = sorted([p for p in dir_path.iterdir() if p.is_dir()])
    files = sorted([
        p for p in dir_path.iterdir() if p.is_file() and p.suffix == ".md" and p.name != "index.md"
    ])

    children: list[str] = []
    for sub in subdirs:
        children.extend(_build_nav_section(sub.name, sub, level + 1, docs_root))
    for md in files:
        rel = md.relative_to(docs_root).as_posix()
        children.append(f"{_nav_indent(level + 1)}- {md.stem}: {rel}")

    if not children:
        return []
    return [f"{_nav_indent(level)}- {title}:", *children]


def _rebuild_nav(
    docs_dir: str, config_path: str, sections: tuple[str, ...] | list[str] | str
) -> None:
    """Rewrite the marker-bounded nav block in `config_path` from `docs_dir`.

    Args:
        docs_dir (str): MkDocs source directory.
        config_path (str): `mkdocs.yml` path to update.
        sections (tuple[str, ...] | list[str] | str): Top-level nav sections to expose.
    """
    docs_root = Path(docs_dir)
    config_file = Path(config_path)

    text = config_file.read_text(encoding="utf-8")
    if _NAV_START not in text or _NAV_END not in text:
        raise SystemExit(
            f"{config_path} is missing the auto-nav markers; expected\n"
            f"  {_NAV_START}\n  {_NAV_END}\n"
            "to delimit the region rewritten by build_nav."
        )

    section_list = [sections] if isinstance(sections, str) else list(sections)

    body_lines: list[str] = []
    for section in section_list:
        body_lines.extend(_build_nav_section(section, docs_root / section, 0, docs_root))

    body = "\n".join(body_lines)
    head, _, rest = text.partition(_NAV_START)
    _, _, tail = rest.partition(_NAV_END)
    config_file.write_text(f"{head}{_NAV_START}\n{body}\n{_NAV_END}{tail}", encoding="utf-8")


class DocsGenerator(BaseModel):
    """Generate module markdown pages and rebuild the MkDocs nav.

    Attributes:
        source_path (Path): Source directory or file path.
        output_path (Path): Output directory path.
        exclude (str): Comma-separated list of folders or files to exclude.
        mode (Literal["file", "class"]): Whether to generate docs by file or class.
        execute (bool): Whether to execute notebooks before converting them.
        concurrency (int): Maximum number of files to process concurrently.

    Examples:
    === "Generate docs pages"
        ```bash
        uv run ./scripts/gen_docs.py --source ./src --output ./docs/Reference gen_docs
        ```

    === "Rebuild mkdocs nav"
        ```bash
        uv run ./scripts/gen_docs.py build_nav
        ```
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)
    source_path: Path = Field(
        ...,
        title="The Source File Path or Folder Path",
        description="This field can be a file path or folder path, if it is a folder path, it will automatically search for python and ipynb files.",
        examples=["./src"],
        alias="source",
        frozen=True,
    )
    output_path: Path = Field(
        ...,
        title="The Output Path",
        description="The output path for the generated documentation.",
        examples=["./docs/Reference"],
        alias="output",
        frozen=True,
    )
    exclude: str = Field(
        default=".venv",
        description="Exclude the folder or file, it should be separated by comma.",
        examples=[".venv,.git,.idea"],
    )
    mode: Literal["file", "class"] = Field(
        default="class",
        title="The Document Style",
        description="Generate docs by file or class.",
        examples=["file", "class"],
    )
    execute: bool = Field(
        default=False,
        title="Execute Notebook",
        description="Execute the notebook before generating the documentation.",
        examples=["True", "False"],
    )
    concurrency: int = Field(
        default=10,
        title="Concurrency Limit",
        description="Maximum number of files to process concurrently.",
        examples=[5, 10, 20],
    )

    def _get_all_files(self, suffix: str) -> list[Path]:
        """Gets all files with the specified suffixes recursively.

        Args:
            suffix (str): Comma-separated suffixes without leading dots.

        Returns:
            list[Path]: Matching files under `source_path`.
        """
        targets = [s.strip() for s in suffix.split(",")]
        all_files: list[Path] = []
        for target in targets:
            filename = list(self.source_path.rglob(f"*.{target}"))
            all_files.extend(filename)
        return all_files

    @computed_field
    @cached_property
    def source_files(self) -> list[Path]:
        """The source files selected for documentation generation.

        Returns:
            list[Path]: Source files under `source_path`, excluding configured entries and
            default skipped paths when `source_path` is a directory. Returns the
            single source file when `source_path` is a file, or an empty list
            when it is neither a valid file nor directory.
        """
        if self.source_path.is_dir():
            if self.output_path.exists():
                shutil.rmtree(self.output_path.absolute())
            exclude_list = [ex.strip() for ex in self.exclude.split(",")]
            need_to_exclude = list({*exclude_list, ".venv", "__init__.py"})
            all_files = self._get_all_files(suffix="py,ipynb")
            all_files = [
                file for file in all_files if not any(f in file.parts for f in need_to_exclude)
            ]
        elif self.source_path.is_file():
            all_files = [self.source_path]
        else:
            all_files = []
            console.log(
                f"[red]Source path {self.source_path} does not exist or is not a valid file or directory."
            )
        return all_files

    async def _prepare_docs_path(self, file: Path) -> Path:
        """Prepares the output directory for the given file.

        Args:
            file (Path): Source file being converted.

        Returns:
            Path: Markdown output path for the source file.
        """
        # Preserve nested source directories under the output path.
        filename = file.with_suffix(".md").name
        if file.parent.as_posix() != ".":
            related_path = file.parent.relative_to(self.source_path)
            docs_path = Path(f"{self.output_path}/{related_path}/{filename}")
        else:
            docs_path = Path(f"{self.output_path}/{filename}")
        docs_path.parent.mkdir(parents=True, exist_ok=True)
        docs_path.unlink(missing_ok=True)
        return docs_path

    async def _gen_python_docs(self, file: Path) -> str:
        """Generates markdown documentation for a Python file.

        Args:
            file (Path): Python source file to document.

        Returns:
            str: Generated Markdown file path.
        """
        docs_path = await self._prepare_docs_path(file=file)
        if self.mode == "file":
            note_content = f"::: {file.with_suffix('').as_posix().replace('/', '.')}\n"
        elif self.mode == "class":
            async with await anyio.open_file(file, encoding="utf-8") as f:
                contents = await f.read()
                tree = ast.parse(source=contents, filename=file)

            note_content = ""
            for node in ast.walk(tree):
                if isinstance(node, ast.ClassDef):
                    note_content += (
                        f"::: {file.with_suffix('').as_posix().replace('/', '.')}.{node.name}\n"
                    )
        else:
            raise ValueError("Invalid mode")
        if not note_content:
            note_content = f"::: {file.with_suffix('').as_posix().replace('/', '.')}\n"
        docs_path.write_text(data=note_content, encoding="utf-8")
        return docs_path.as_posix()

    async def _gen_notebook_docs(self, file: Path) -> str:
        """Generates markdown documentation for a Jupyter notebook.

        Args:
            file (Path): Notebook file to convert.

        Returns:
            str: Generated Markdown file path.
        """
        docs_path = await self._prepare_docs_path(file=file)
        async with await anyio.open_file(file, encoding="utf-8") as f:
            notebook_content = nbformat.reads(await f.read(), as_version=4)

        if self.execute:
            execute_preprocessor = ExecutePreprocessor(
                timeout=600,
                kernel_name="python3",
                allow_errors=True,
                store_widget_state=True,
                record_timing=True,
            )
            if not isinstance(execute_preprocessor, ExecutePreprocessor):
                raise TypeError("ExecutePreprocessor is not a valid type")
            execute_preprocessor.preprocess(
                notebook_content, {"metadata": {"path": file.parent.as_posix()}}
            )

        markdown_exporter = MarkdownExporter(template_name="markdown")
        if not isinstance(markdown_exporter, MarkdownExporter):
            raise TypeError("TemplateExporter is not a valid type")
        markdown_output, _ = markdown_exporter.from_notebook_node(notebook_content)
        async with await anyio.open_file(docs_path, "w", encoding="utf-8") as f:
            await f.write(markdown_output)
        return docs_path.as_posix()

    async def _process_file(self, file: Path, progress: Progress, task: TaskID) -> str:
        """Process a single file and update progress.

        Args:
            file (Path): Source file to convert.
            progress (Progress): Progress renderer to update.
            task (TaskID): Progress task identifier.

        Returns:
            str: Generated Markdown file path, or an empty string on failure.
        """
        try:
            if file.suffix == ".ipynb":
                result = await self._gen_notebook_docs(file=file)
            elif file.suffix == ".py":
                result = await self._gen_python_docs(file=file)
            else:
                console.log(f"Unsupported file type: {file.suffix}")
                result = ""

            progress.update(task, advance=1, description=f"[cyan]Processed {file.name}")
            return result
        except Exception as e:
            console.log(f"[red]Error processing {file}: {e!s}")
            progress.update(task, advance=1, description=f"[red]Failed {file.name}")
            return ""

    async def _process_batch(
        self, files: list[Path], progress: Progress, task: TaskID
    ) -> list[str]:
        """Process a batch of files with the configured concurrency limit.

        Args:
            files (list[Path]): Source files to convert.
            progress (Progress): Progress renderer to update.
            task (TaskID): Progress task identifier.

        Returns:
            list[str]: Generated Markdown file paths, with empty strings for failures.
        """
        semaphore = asyncio.Semaphore(self.concurrency)

        async def process_with_semaphore(file: Path) -> str:
            """Processes one file while respecting the configured concurrency limit."""
            async with semaphore:
                return await self._process_file(file, progress, task)

        tasks = [process_with_semaphore(file) for file in files]
        return await asyncio.gather(*tasks)

    async def gen_docs(self) -> None:
        """Generates per-module markdown pages from the source files."""
        with Progress() as progress:
            total_files = len(self.source_files)
            task = progress.add_task(f"[green]Generating {total_files}...", total=total_files)

            if not self.source_files:
                console.log("[yellow]No files found to process")
                return

            results = await self._process_batch(self.source_files, progress, task)

            successful = len([r for r in results if r])
        console.log(
            f"[green]Documentation generation complete ({successful}/{total_files})!",
            highlight=True,
        )

    @staticmethod
    def build_nav(
        docs_dir: str = "docs",
        config_path: str = "mkdocs.yml",
        sections: tuple[str, ...] = ("Reference", "Scripts"),
    ) -> None:
        """Rewrite the auto-generated MkDocs nav block by scanning the docs tree.

        The script walks each requested top-level section under `docs_dir` and
        emits a nested nav YAML structure so the sidebar shows every leaf module
        directly. It rewrites only the region delimited by the sentinel comments
        in `config_path`; everything outside the markers is preserved verbatim.

        Exposed as a `@staticmethod` so Fire can dispatch
        `gen_docs.py build_nav` without instantiating `DocsGenerator` (which
        would require `--source` / `--output` that are irrelevant here).

        Args:
            docs_dir (str): Path to the MkDocs source directory (where `index.md` lives).
            config_path (str): Path to the `mkdocs.yml` to update in-place.
            sections (tuple[str, ...]): Top-level directory names under `docs_dir` to expose as
                expandable nav sections. Sections that do not exist on disk are
                silently skipped.
        """
        _rebuild_nav(docs_dir=docs_dir, config_path=config_path, sections=sections)


if __name__ == "__main__":
    import fire

    fire.Fire(DocsGenerator)
