# This workflow finds which files were changed, prints them,
# and runs `pre-commit` on those files.

# Inspired by the sktime library:
# https://github.com/alan-turing-institute/sktime/blob/main/.github/workflows/test.yml

name: Code Quality Check

on:
  pull_request:

permissions: write-all

jobs:
  code-quality-check:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pre-commits
        run: |
          uvx pre-commit run -a
